### ISSUE TITLE
Add the ability to remove all country blocks?

### ISSUE THREAD

**Issue by nsuchy** [afterdead/Cloudflare-API-Add-Captcha-All-Country-To-CSF#2]
If you have time would you mind adding another script that removes all the country rules (Currently you can whitelist the countries to get around removing them one by one, but I'd like to have a script that just removes all of the rules), would you be willing to implement this?

**Comment by duy13** [comment]
Try this script: https://github.com/duy13/vDDoS-Layer4-Mapping/tree/master/opensource

**Comment by nsuchy** [comment]
I don't want to install the entire vDDoS System but those shell scripts look useful, I'll save them and use as needed :)

**Comment by nsuchy** [comment]
The author doesn't appear to have made any recent commits since 2016 so I'm closing this issue in favor of some node scripts I wrote to accomplish the desired tasks.
